module.exports = {
  BACKBLAZE_B2_ACCOUNT_ID: process.env.GATE_BACKBLAZE_B2_ACCOUNT_ID,
  BACKBLAZE_B2_APPLICATION_KEY: process.env.GATE_BACKBLAZE_B2_APPLICATION_KEY,

  BUCKET_NAME: "api-test-bucket",

  TEMP_DIRECTORY: "./tmp",
  THUMBNAIL_DIRECTORY: "./thumbnails"
};
